src/AcMarche/Avaloir/Entity/Avaloir.php
<?php

namespace AcMarche\Avaloir\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TimestampableInterface;
use Knp\DoctrineBehaviors\Model\Timestampable\TimestampableTrait;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="AcMarche\Avaloir\Repository\AvaloirRepository")
 * @ORM\Table(name="avaloir")
 * @Vich\Uploadable
 *
 */
class Avaloir implements TimestampableInterface
{
    use TimestampableTrait;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=8, nullable=false)
     */
    protected $latitude;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=8, nullable=false)
     */
    protected $longitude;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $description;

    /**
     * @ORM\Column(type="string", length=120, nullable=true)
     *
     */
    protected $rue;

    /**
     * @ORM\Column(type="string", length=120, nullable=true)
     *
     */
    protected $localite;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $numero;

    /**
     * @ORM\OneToMany(targetEntity="DateNettoyage", mappedBy="avaloir", cascade={"persist", "remove"}))
     * @ORM\OrderBy({"jour"="DESC"})
     */
    private $dates;

    /**
     * @ORM\OneToMany(targetEntity="Commentaire", mappedBy="avaloir", cascade={"persist", "remove"}))
     * @ORM\OrderBy({"createdAt"="DESC"})
     */
    private $commentaires;

    /**
     * @ORM\Column(type="date", nullable=true, options={"comment" = "date de rappel"})
     * @Assert\Type("DateTime")
     */
    protected $date_rappel;

    /**
     *
     * @Vich\UploadableField(mapping="avaloir_image", fileNameProperty="imageName")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=120, nullable=true)
     */
    private $imageName;

    public function __construct()
    {
        $this->dates = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->rue . " " . $this->numero;
    }

    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     * @throws \Exception
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(string $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    public function setLongitude(string $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getRue(): ?string
    {
        return $this->rue;
    }

    public function setRue(?string $rue): self
    {
        $this->rue = $rue;

        return $this;
    }

    public function getLocalite(): ?string
    {
        return $this->localite;
    }

    public function setLocalite(?string $localite): self
    {
        $this->localite = $localite;

        return $this;
    }

    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(?string $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getDateRappel(): ?\DateTimeInterface
    {
        return $this->date_rappel;
    }

    public function setDateRappel(?\DateTimeInterface $date_rappel): self
    {
        $this->date_rappel = $date_rappel;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     * @return Collection|DateNettoyage[]
     */
    public function getDates(): Collection
    {
        return $this->dates;
    }

    public function addDate(DateNettoyage $date): self
    {
        if (!$this->dates->contains($date)) {
            $this->dates[] = $date;
            $date->setAvaloir($this);
        }

        return $this;
    }

    public function removeDate(DateNettoyage $date): self
    {
        if ($this->dates->contains($date)) {
            $this->dates->removeElement($date);
            // set the owning side to null (unless already changed)
            if ($date->getAvaloir() === $this) {
                $date->setAvaloir(null);
            }
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setAvaloir($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->contains($commentaire)) {
            $this->commentaires->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getAvaloir() === $this) {
                $commentaire->setAvaloir(null);
            }
        }

        return $this;
    }



}

src/AcMarche/Avaloir/Form/AvaloirType.php
<?php

namespace AcMarche\Avaloir\Form;

use AcMarche\Avaloir\Entity\Avaloir;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AvaloirType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'dates',
                CollectionType::class,
                array(
                    'entry_type' => DateNettoyageType::class,
                    'required' => false,
                    'allow_add' => false,
                    'label' => ' ',
                    'prototype' => true,
                    'allow_delete' => false,
                )
            )
            ->add(
                'rue',
                TextType::class,
                array(
                    'required' => true,
                    'mapped' => false,
                    'attr' => array('class' => 'typeahead'),
                )
            )
            ->add(
                'numero',
                TextType::class,
                [
                    'required' => false,
                    'help' => 'Emplacement approximatif dans la rue',
                ]
            )
            ->add(
                'descriptif',
                TextareaType::class,
                array(
                    'required' => false,
                    'attr' => array('rows' => 5),
                )
            )
            ->add(
                'date_rappel',
                DateType::class,
                array(
                    'widget' => 'single_text',
                    'required' => false,
                    'label' => 'Date de rappel',
                    'attr' => array('autocomplete' => 'off'),
                )
            );
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => Avaloir::class,
            )
        );
    }
}

src/AcMarche/Avaloir/Controller/AvaloirController.php
<?php


namespace AcMarche\Avaloir\Controller;

use AcMarche\Avaloir\Entity\Avaloir;
use AcMarche\Avaloir\Entity\DateNettoyage;
use AcMarche\Avaloir\Entity\Rue;
use AcMarche\Avaloir\Form\AvaloirEditType;
use AcMarche\Avaloir\Form\AvaloirType;
use AcMarche\Avaloir\Form\LocalisationType;
use AcMarche\Avaloir\Form\Search\SearchAvaloirType;
use AcMarche\Avaloir\Repository\AvaloirRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Avaloir controller.
 *
 * @IsGranted("ROLE_TRAVAUX_AVALOIR")
 *
 * @Route("/avaloir")
 */
class AvaloirController extends AbstractController
{
    /**
     * @var AvaloirRepository
     */
    private $avaloirRepository;

    public function __construct(
        AvaloirRepository $avaloirRepository
    ) {
        $this->avaloirRepository = $avaloirRepository;
    }

    /**
     * Lists all Avaloir entities.
     *
     * @Route("/", name="avaloir", methods={"GET"})
     *
     */
    public function index(Request $request)
    {
        $session = $request->getSession();
        $key = 'avaloir_search';
        $session->remove($key);
        $search_form = $this->createForm(
            SearchAvaloirType::class,
            [],
            array(
                'action' => $this->generateUrl('avaloir'),
                'method' => 'GET',
            )
        );

        $search_form->handleRequest($request);

        if ($search_form->isSubmitted() && $search_form->isValid()) {
            $data = $search_form->getData();
            $session->set($key, serialize($data));
            $avaloirs = $this->avaloirRepository->search($data);
        } else {
            $avaloirs = $this->avaloirRepository->search([]);
        }

        return $this->render(
            '@AcMarcheAvaloir/avaloir/index.html.twig',
            array(
                'search_form' => $search_form->createView(),
                'avaloirs' => $avaloirs,
            )
        );
    }

    /**
     * Displays a form to create a new Avaloir entity.
     *
     * Route("/new", name="avaloir_new", methods={"GET","POST"})
     *
     */
    public function new(Request $request)
    {
        $avaloir = new Avaloir();
        $jour = new DateNettoyage();
        $avaloir->addDate($jour);

        $form = $this->createForm(AvaloirType::class, $avaloir)
            ->add('Create', SubmitType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $data = $form->getData();
            $rueId = $data->getRueId();
            $dates = $data->getDates();

            if ($dates[0] instanceof DateNettoyage) {
                $jour2 = $dates[0]->getJour();
                if ($jour2) {
                    $jour->setAvaloir($avaloir);
                } else {
                    $avaloir->removeDate($jour);
                }
            }

            $rue = false;
            if ($rueId) {
                $rue = $em->getRepository(Rue::class)->find($rueId);
            }

            if (!$rue) {
                $this->addFlash("error", "La rue que vous avez choisi ne se trouve pas dans la liste des rues");

                return $this->redirectToRoute('avaloir_show');
            }

            $avaloir->setRue($rue);
            $em->persist($avaloir);
            $em->flush();
            $this->addFlash("success", "L'avaloir a bien été créé");

            return $this->redirectToRoute('avaloir_show', ['id' => $avaloir->getId()]);
        }

        return $this->render(
            '@AcMarcheAvaloir/avaloir/new.html.twig',
            array(
                'entity' => $avaloir,
                'form' => $form->createView(),
            )
        );
    }

    /**
     * Finds and displays a Avaloir entity.
     *
     * @Route("/{id}", name="avaloir_show", methods={"GET"})
     *
     */
    public function show(Avaloir $avaloir)
    {
        $form = $this->createForm(
            LocalisationType::class,
            $avaloir,
            [
                'action' => $this->generateUrl('avaloir_localisation_update', ['id' => $avaloir->getId()]),
            ]
        );

        return $this->render(
            '@AcMarcheAvaloir/avaloir/show.html.twig',
            array(
                'avaloir' => $avaloir,
                'form' => $form->createView(),
            )
        );
    }

    /**
     * Displays a form to edit an existing Avaloir entity.
     *
     * @Route("/{id}/edit", name="avaloir_edit", methods={"GET","POST"})
     *
     */
    public function edit(Request $request, Avaloir $avaloir)
    {
        $em = $this->getDoctrine()->getManager();

        $editForm = $this->createForm(AvaloirEditType::class, $avaloir)
            ->add('Update', SubmitType::class);

        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $em->flush();
            $this->addFlash("success", "L'avaloir a bien été modifié");

            return $this->redirectToRoute('avaloir_show', array('id' => $avaloir->getId()));
        }

        return $this->render(
            '@AcMarcheAvaloir/avaloir/edit.html.twig',
            array(
                'avaloir' => $avaloir,
                'edit_form' => $editForm->createView(),
            )
        );
    }

    /**
     * Deletes a Avaloir entity.
     *
     * @Route("/{id}", name="avaloir_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Avaloir $avaloir)
    {
        if ($this->isCsrfTokenValid('delete'.$avaloir->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($avaloir);
            $em->flush();
            $this->addFlash("success", "L'avaloir a bien été supprimé");
        }

        return $this->redirectToRoute('avaloir');
    }

}

src/AcMarche/Avaloir/templates/avaloir/_carte.html.twig
{% if avaloir.latitude and avaloir.longitude %}

    <h4>Situation sur la carte</h4>
    {{ include('@AcMarcheAvaloir/avaloir/_localisation_form.html.twig') }}

    <div id='openmap' style='width: 100%; height: 400px;'></div>

    <script type="text/javascript">
        var latitude = '{{ avaloir.latitude }}';
        var longitude = '{{ avaloir.longitude }}';
        var center = [latitude, longitude];
        var map = L.map('openmap').setView(center, 18);
        var societe = '{{ avaloir.rue }}';

        L.tileLayer('https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png', {
            // Il est toujours bien de laisser le lien vers la source des données
            attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
            minZoom: 1,
            maxZoom: 20
        }).addTo(map);

        var marker = L.marker(center, {title: societe, draggable: true}).addTo(map);

        marker.on('dragend', function (e) {
            document.getElementById('localisation_latitude').value = marker.getLatLng().lat;
            document.getElementById('localisation_longitude').value = marker.getLatLng().lng;
        });

    </script>

{% endif %}

src/AcMarche/Avaloir/templates/avaloir/_commentaires.html.twig
<h4>Liste des commentaires</h4>

<table class="table table-border">
    {% for commentaire in avaloir.commentaires %}
        <tr>
            <td>
                {{ commentaire.content | nl2br }}
            </td>
            <td>
                {{ commentaire.createdAt | format_date('full') }}
            </td>
        </tr>
    {% endfor %}
</table>

src/AcMarche/Avaloir/templates/avaloir/_dates_nettoyages.html.twig
<br/>
<h4>Liste des dates de nettoyages</h4>

<ul class='list-group'>
    {% for date in avaloir.dates %}
        {% set datenettoyage = date.jour %}
        <li class='list-group-item'>
            <a title='' href='{{ path('datenettoyage_show', { 'id': date.id }) }}'>
                {{ datenettoyage | date('d-m-Y') }}
            </a>
        </li>
    {% else %}
        <li class='list-group-item'>Aucune</li>
    {% endfor %}
</ul>
<br/>

src/AcMarche/Avaloir/templates/avaloir/_images.html.twig
{% if avaloir.imageName %}

    <img src="{{ vich_uploader_asset(avaloir, 'imageFile') | imagine_filter('avaloir_heighten_filter') }}"
         alt="{{ avaloir.imageName }}" class="card-img-top"/>
    <br/>    <br/>

{% else %}
    <svg class="bd-placeholder-img" width="100%" height="250" xmlns="http://www.w3.org/2000/svg"
         preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Image"><title>
            Photo de l'enfant</title>
        <rect width="100%" height="100%" fill="#868e96"></rect>
        <text x="50%" y="50%" fill="#dee2e6" dy=".3em">Image</text>
    </svg>

{% endif %}
<br/>

src/AcMarche/Avaloir/templates/avaloir/_localisation_form.html.twig
{{ form_start(form) }}
{{ form_errors(form) }}
<div class="form-row">
    <div class="col">
        {{ form_widget(form.latitude) }}
    </div>
    <div class="col">
        {{ form_widget(form.longitude) }}
    </div>
    <div class="col">
        <button class="btn btn-primary ml-1 mb-2" type="submit"><i class="far fa-save" aria-hidden="true"></i>
            Sauvegarder
        </button>
    </div>
</div>
<span class="text-muted">Déplacer le curseur pour corriger la localisation</span>
{{ form_end(form) }}

src/AcMarche/Avaloir/templates/avaloir/actions.html.twig
{% if is_granted('ROLE_TRAVAUX_AVALOIR') %}

    <a href="{{ path('avaloir') }}" class="btn btn-primary" role="button"><i
                class="fas fa-arrow-left"></i>
        Retour à la liste</a>

    <a href="{{ path('datenettoyage_new', { 'id': avaloir.id }) }}" class="btn btn-primary" role="button"><i
                class="far fa-calendar-alt"></i>
        Ajouter une date de nettoyage</a>

    <a href="{{ path('commentaire_new', { 'id': avaloir.id }) }}" class="btn btn-primary" role="button">
        <i class="far fa-comment-dots"></i>
        Ajouter un commentaire</a>

    <a href="{{ path('avaloir_edit', { 'id': avaloir.id }) }}" class="btn btn-primary" role="button"><i
                class="far fa-edit"></i>
        Editer</a>

    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">
        <i class="fas fa-trash"></i> Supprimer l'avaloir
    </button>
    <br/>
{% endif %}

src/AcMarche/Avaloir/templates/avaloir/delete.html.twig
{% if is_granted('ROLE_TRAVAUX_AVALOIR') %}
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Confirmer la suppression d'un avaloir</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Etes vous sur de vouloir <strong>supprimer</strong> <br/> l'avaloir <strong>{{ avaloir }} ? </strong>
                </div>
                <div class="modal-footer">
                    <form method="post" action="{{ path('avaloir_delete', {'id': avaloir.id}) }}">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ avaloir.id) }}">
                        <button type="button" class="btn btn-secondary"
                                data-dismiss="modal">Annuler
                        </button>
                        <button type="submit"
                                class="btn btn-danger">Supprimer
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endif %}

src/AcMarche/Avaloir/templates/avaloir/edit.html.twig
{% extends '@AcMarcheAvaloir/layout_avaloir.html.twig' %}

{% block body -%}

    <div class="page-header">
        <h3>Edition de l'avaloir {{ avaloir.id }} {{ avaloir.rue }}</h3>
    </div>

    <div class="card bg-light">
        <div class="card-header">
            {{ form(edit_form) }}
        </div>
    </div>

{% endblock %}

src/AcMarche/Avaloir/templates/avaloir/index.html.twig
{% extends '@AcMarcheAvaloir/layout_avaloir.html.twig' %}

{% block body -%}
    <div class="page-header">
        <h3>Liste des avaloirs ({{ avaloirs | length }}) </h3>
    </div>

    {% include '@AcMarcheAvaloir/search/avaloir.html.twig' %}

    {% if avaloirs | length > 0 %}
        <div class="row row-cols-1 row-cols-md-3">
            {% for avaloir in avaloirs %}
                <div class="col mb-4">
                    <div class="card h-100">
                        <div class="card-header">
                            <a title="Consulter l'avaloir" href="{{ path('avaloir_show', { 'id': avaloir.id }) }}">
                                {{ avaloir.rue }} {{ avaloir.numero }}
                            </a>
                        </div>
                        {% if avaloir.imageName %}
                            <img src="{{ vich_uploader_asset(avaloir, 'imageFile') | imagine_filter('avaloir_heighten_filter') }}"
                                 alt="{{ avaloir.imageName }}" class="card-img-top"/>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">
                                <a title="Consulter l'avaloir" href="{{ path('avaloir_show', { 'id': avaloir.id }) }}">
                                    {{ avaloir.rue }} {{ avaloir.numero }} <br/> {{ avaloir.localite }}
                                </a>
                            </h5>

                            {% if avaloir.dateRappel and avaloir.dateRappel > date('-3days') %}
                                <strong class="text-danger">Date de rappel :</strong> {{ avaloir.dateRappel | format_date('full') }}
                            {% endif %}

                            {% if avaloir.commentaires | length > 0 %}
                                <p class="card-text">
                                    <small class="text-muted">
                                        {% set commentaire = avaloir.commentaires | first %}
                                        {{ commentaire.content | nl2br }}
                                    </small>
                                </p>
                            {% endif %}
                        </div>
                        <div class="card-footer text-muted">
                            {% if avaloir.dates | length > 0 %}
                                {% set jour = avaloir.dates | first %}
                                Dernier nettoyage le {{ jour | format_date('full') }}
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

src/AcMarche/Avaloir/templates/avaloir/new.html.twig
{% extends '@AcMarcheAvaloir/layout_avaloir.html.twig' %}

{% block stylesheets %}
    <link href="{{ asset('bundles/acmarchetravaux/jquery-ui/jquery-ui.min.css') }}" rel="stylesheet">
    <link href="{{ asset('bundles/acmarchetravaux/css/typeahead.css') }}" rel="stylesheet">
{% endblock %}

{% block body -%}

    <div class="page-header">
        <h3>Nouvel avaloir</h3>
    </div>

    <div class="card bg-light">
        <div class="card-header">

            {{ form_start(form, { 'attr': {'class': 'well'} }) }}
            {{ form_errors(form) }}
            {{ form_row(form.rue) }}
            {{ form_row(form.numero) }}
            {% for dateField in form.dates %}
                {{ form_errors(dateField) }}
                {{ form_widget(dateField) }}
            {% endfor %}
            {{ form_row(form.descriptif) }}
            {{ form_end(form) }}
        </div>
    </div>

{% endblock %}
{% block scripts %}

    <script type="text/javascript">

        //set hidden field
        function gotoRue(obj, data) {
            $('#avaloir_rueId').val(data.value);
        }

        function initTypeahead() {
            var rues = new Bloodhound({
                datumTokenizer: function (datum) {
                    return Bloodhound.tokenizers.whitespace(datum.label);
                },
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                remote: {
                    url: '{{ path('rue_autocomplete') }}/%QUERY',
                    wildcard: '%QUERY'
                }
            });

            var options = {
                hint: true,
                highlight: true,
                minLength: 2
            };

            var dataSet = {
                display: 'label',
                limit: 10,
                source: rues,
                templates: {
                    suggestion: function (data) {
                        return '<p>' + data.label + ' (' + data.village + ')</p>';
                    }
                }
            };


            $('.typeahead').typeahead(options, dataSet)
                .bind('typeahead:selected', function (obj, data) {
                    gotoRue(obj, data);
                })
                .bind('typeahead:autocompleted', function (obj, data) {
                    gotoRue(obj, data);
                });
        }
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            initTypeahead();
        });
    </script>

{% endblock %}

src/AcMarche/Avaloir/templates/avaloir/show.html.twig
{% extends '@AcMarcheAvaloir/layout_avaloir.html.twig' %}

{% block body -%}

    <div class="card bg-light mb-3">

        <div class="card-header">
            <h3>Avaloir <strong>{{ avaloir.rue }}</strong></h3>
        </div>

        <div class="card-body">

            {% include '@AcMarcheAvaloir/avaloir/actions.html.twig' %}

            <div class="row no-gutters pl-1">
                <div class="col-md-4 mt-4">
                    {{ include('@AcMarcheAvaloir/avaloir/_images.html.twig') }}
                </div>
                <div class="col-md-7 mt-4 ml-1">
                    <table class="table table-bordered">
                        <tr>
                            <th>Localisation</th>
                            <td>
                                <a href="https://www.openstreetmap.org/#map=17/{{ avaloir.latitude }}/{{ avaloir.longitude }}"
                                   target="_blank">
                                    {{ avaloir.latitude }}, {{ avaloir.longitude }}
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <th>Localité</th>
                            <td>
                                {{ avaloir.localite }}
                            </td>
                        </tr>
                        <tr>
                            <th>Date de rappel</th>
                            <td>
                                {% if avaloir.dateRappel %}
                                    {{ avaloir.dateRappel | format_date('full') }}
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <th>Id</th>
                            <td>{{ avaloir.id }}</td>
                        </tr>
                    </table>

                    <p>{{ avaloir.description | nl2br }}</p>
                </div>
            </div>

            {{ include('@AcMarcheAvaloir/avaloir/_carte.html.twig') }}

            {{ include('@AcMarcheAvaloir/avaloir/_dates_nettoyages.html.twig') }}

            {{ include('@AcMarcheAvaloir/avaloir/_commentaires.html.twig') }}

        </div>
        <div class="card-footer text-muted">
            {{ 'Created' | trans }} {{ avaloir.createdAt|format_date('full','full') }}
            . {{ 'Updated' | trans }} {{ avaloir.updatedAt|format_date('full','full') }}
        </div>
    </div>

    {% include '@AcMarcheAvaloir/avaloir/delete.html.twig' %}

{% endblock %}