src/AcMarche/Travaux/src/Entity/Intervention.php
<?php

namespace AcMarche\Travaux\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TimestampableInterface;
use Knp\DoctrineBehaviors\Model\Timestampable\TimestampableTrait;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="AcMarche\Travaux\Repository\InterventionRepository")
 * @ORM\Table(name="intervention")
 *
 */
class Intervention implements TimestampableInterface
{
    use TimestampableTrait;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", nullable=false)
     * @ORM\OrderBy({"intitule"="ASC"})
     * @Assert\NotBlank()
     * @var string
     */
    protected $intitule;

    /**
     * @ORM\ManyToOne(targetEntity="AcMarche\Travaux\Entity\Etat", inversedBy="interventions")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $etat;

    /**
     * @ORM\ManyToOne(targetEntity="AcMarche\Travaux\Entity\Priorite", inversedBy="interventions")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $priorite;

    /**
     * @ORM\Column(type="boolean", nullable=false, options={"default"=0} )
     */
    protected $transmis = false;

    /**
     * @ORM\Column(type="date", nullable=false)
     */
    protected $date_introduction;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    protected $date_rappel;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    protected $date_execution;

    /**
     * @ORM\Column(type="text", nullable=false)
     */
    protected $descriptif;

    /********************
     * AFFECTATION
     * ******************
     */

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $affectation;

    /**
     * @ORM\Column(type="boolean", nullable=false, options={"default"=0} )
     */
    protected $affecte_prive = false;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    protected $soumis_le;

    /********************
     * SOLUTION
     * ******************
     */

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $solution;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    protected $date_solution;

    /**
     * @ORM\Column(type="boolean", nullable=false, options={"default"=0} )
     */
    protected $archive = false;

    /**
     * @ORM\Column(type="decimal", precision=9, scale=2, nullable=true)
     */
    protected $cout_main;

    /**
     * @ORM\Column(type="decimal", precision=9, scale=2, nullable=true)
     */
    protected $cout_materiel;

    /**
     *
     * @ORM\Column(type="date", nullable=true)
     */
    protected $date_validation;

    /**
     * @ORM\Column(type="boolean", nullable=false, options={"default"=0} )
     */
    protected $smartphone = false;

    /**
     * @ORM\Column(type="string", nullable=false)
     */
    protected $user_add;

    /**
     * @ORM\ManyToOne(targetEntity="Domaine", inversedBy="intervention")
     * @ORM\JoinColumn(nullable=true, onDelete="SET NULL")
     */
    protected $domaine;

    /**
     * @ORM\ManyToOne(targetEntity="Batiment", inversedBy="intervention")
     * @ORM\JoinColumn(nullable=true, onDelete="SET NULL")
     */
    protected $batiment;

    /**
     * @ORM\ManyToOne(targetEntity="Service", inversedBy="intervention")
     * @ORM\JoinColumn(nullable=true, onDelete="SET NULL")
     */
    protected $service;

    /**
     * @ORM\ManyToOne(targetEntity="Categorie", inversedBy="intervention")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $categorie;

    /**
     * @ORM\OneToMany(targetEntity="Document", mappedBy="intervention", cascade="remove")
     *
     */
    protected $documents;

    /**
     * @ORM\OneToMany(targetEntity="AcMarche\Travaux\Entity\Suivi", mappedBy="intervention", cascade="remove")
     * @ORM\OrderBy({"id" = "DESC"})
     */
    protected $suivis;

    /**
     * This property is used by the marking store
     * @ORM\Column(type="string", nullable=true)
     */
    public $currentPlace;

    public function __toString()
    {
        return $this->intitule;
    }

    /**
     * @var Suivi|null
     */
    protected $lastSuivi;

    /**
     * @return Suivi
     */
    public function getLastSuivi() : ?Suivi
    {
        return $this->lastSuivi;
    }

    /**
     * @param Suivi $lastSuivis
     */
    public function setLastSuivi(?Suivi $lastSuivi)
    {
        $this->lastSuivi = $lastSuivi;
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->date_introduction = new \DateTime();
        $this->documents = new ArrayCollection();
        $this->suivis = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntitule(): ?string
    {
        return $this->intitule;
    }

    public function setIntitule(string $intitule): self
    {
        $this->intitule = $intitule;

        return $this;
    }

    public function getTransmis(): ?bool
    {
        return $this->transmis;
    }

    public function setTransmis(bool $transmis): self
    {
        $this->transmis = $transmis;

        return $this;
    }

    public function getDateIntroduction(): ?\DateTimeInterface
    {
        return $this->date_introduction;
    }

    public function setDateIntroduction(\DateTimeInterface $date_introduction): self
    {
        $this->date_introduction = $date_introduction;

        return $this;
    }

    public function getDateRappel(): ?\DateTimeInterface
    {
        return $this->date_rappel;
    }

    public function setDateRappel(?\DateTimeInterface $date_rappel): self
    {
        $this->date_rappel = $date_rappel;

        return $this;
    }

    public function getDateExecution(): ?\DateTimeInterface
    {
        return $this->date_execution;
    }

    public function setDateExecution(?\DateTimeInterface $date_execution): self
    {
        $this->date_execution = $date_execution;

        return $this;
    }

    public function getDescriptif(): ?string
    {
        return $this->descriptif;
    }

    public function setDescriptif(string $descriptif): self
    {
        $this->descriptif = $descriptif;

        return $this;
    }

    public function getAffectation(): ?string
    {
        return $this->affectation;
    }

    public function setAffectation(?string $affectation): self
    {
        $this->affectation = $affectation;

        return $this;
    }

    public function getAffectePrive(): ?bool
    {
        return $this->affecte_prive;
    }

    public function setAffectePrive(bool $affecte_prive): self
    {
        $this->affecte_prive = $affecte_prive;

        return $this;
    }

    public function getSoumisLe(): ?\DateTimeInterface
    {
        return $this->soumis_le;
    }

    public function setSoumisLe(?\DateTimeInterface $soumis_le): self
    {
        $this->soumis_le = $soumis_le;

        return $this;
    }

    public function getSolution(): ?string
    {
        return $this->solution;
    }

    public function setSolution(?string $solution): self
    {
        $this->solution = $solution;

        return $this;
    }

    public function getDateSolution(): ?\DateTimeInterface
    {
        return $this->date_solution;
    }

    public function setDateSolution(?\DateTimeInterface $date_solution): self
    {
        $this->date_solution = $date_solution;

        return $this;
    }

    public function getArchive(): ?bool
    {
        return $this->archive;
    }

    public function setArchive(bool $archive): self
    {
        $this->archive = $archive;

        return $this;
    }

    public function getCoutMain(): ?string
    {
        return $this->cout_main;
    }

    public function setCoutMain(?string $cout_main): self
    {
        $this->cout_main = $cout_main;

        return $this;
    }

    public function getCoutMateriel(): ?string
    {
        return $this->cout_materiel;
    }

    public function setCoutMateriel(?string $cout_materiel): self
    {
        $this->cout_materiel = $cout_materiel;

        return $this;
    }

    public function getDateValidation(): ?\DateTimeInterface
    {
        return $this->date_validation;
    }

    public function setDateValidation(?\DateTimeInterface $date_validation): self
    {
        $this->date_validation = $date_validation;

        return $this;
    }

    public function getSmartphone(): ?bool
    {
        return $this->smartphone;
    }

    public function setSmartphone(bool $smartphone): self
    {
        $this->smartphone = $smartphone;

        return $this;
    }

    public function getUserAdd(): ?string
    {
        return $this->user_add;
    }

    public function setUserAdd(string $user_add): self
    {
        $this->user_add = $user_add;

        return $this;
    }

    public function getCurrentPlace(): ?string
    {
        return $this->currentPlace;
    }

    public function setCurrentPlace(?string $currentPlace): self
    {
        $this->currentPlace = $currentPlace;

        return $this;
    }

    public function getEtat(): ?Etat
    {
        return $this->etat;
    }

    public function setEtat(?Etat $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getPriorite(): ?Priorite
    {
        return $this->priorite;
    }

    public function setPriorite(?Priorite $priorite): self
    {
        $this->priorite = $priorite;

        return $this;
    }

    public function getDomaine(): ?Domaine
    {
        return $this->domaine;
    }

    public function setDomaine(?Domaine $domaine): self
    {
        $this->domaine = $domaine;

        return $this;
    }

    public function getBatiment(): ?Batiment
    {
        return $this->batiment;
    }

src/AcMarche/Travaux/templates/travaux/intervention/actions.html.twig
<div class="d-print-none">

    <a href="{{ path('intervention_anchor', {'anchor' : intervention.id }) }}#{{ intervention.id }}"
       class="btn btn-primary"
       role="button"><i class="fas fa-list"></i> Retour à la liste</a>

    {% if is_granted('ROLE_TRAVAUX_ADD') %}

        <a href="{{ path('intervention_edit', { 'id': intervention.id }) }}" class="btn btn-primary"
           role="button"><i class="far fa-edit"></i> Editer</a>

        <a href="{{ path('document_new', { 'id': intervention.id }) }}" class="btn btn-primary" role="button"><i
                    class="fa fa-plus"></i> Joindre un fichier</a>
    {% endif %}

    <a href="{{ path('suivi_new', { 'id': intervention.id }) }}" class="btn btn-primary" role="button"><i
                class="fa fa-plus"></i> Ajouter un suivi</a>

    <a href="javascript:window.print();" class="btn btn-primary" role="button">
        <i class="fas fa-print"></i> Imprimer</a>

    {% if is_granted('ROLE_TRAVAUX_ADMIN') or is_granted('ROLE_TRAVAUX_REDACTEUR') %}

        {% if intervention.archive %}
            <a href="#" class="btn btn-warning" role="button" data-toggle="modal"
               data-target="#archiveModal">
                <i class="far fa-file-archive"></i> Désarchiver
            </a>
        {% else %}
            <a href="#" class="btn btn-warning" role="button" data-toggle="modal"
               data-target="#archiveModal">
                <i class="fas fa-archive"></i> Archiver
            </a>
        {% endif %}

        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">
            <i class="fas fa-trash"></i> Supprimer l'intervention
        </button>

    {% endif %}
</div>
<br/>

src/AcMarche/Travaux/templates/travaux/intervention/actions_suvi.html.twig
{% if app.user.username == suivi.useradd %}
    <div class="float-right d-print-none">

        <a href="{{ path('suivi_edit', { 'id': suivi.id }) }}"
           class="btn btn-primary btn-sm"
           role="button"><i class="far fa-edit"></i> Editer</a> | <input type="checkbox" name="suivis[]" value="{{ suivi.id }}" class="checkbox"/>
    </div>
{% endif %}

src/AcMarche/Travaux/templates/travaux/intervention/delete.html.twig
{% if is_granted('ROLE_TRAVAUX_ADMIN') %}
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Confirmer la suppression</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Etes vous sur de vouloir <strong>supprimer</strong> <br/> <strong>{{ intervention }} ? </strong>
                </div>
                <div class="modal-footer">
                    <form method="post" action="{{ path('intervention_delete', {'id': intervention.id}) }}">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ intervention.id) }}">
                        <button type="button" class="btn btn-secondary"
                                data-dismiss="modal">Annuler
                        </button>
                        <button type="submit"
                                class="btn btn-danger">Supprimer
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endif %}

src/AcMarche/Travaux/templates/travaux/intervention/documents.html.twig
{% if intervention.documents | length > 0 %}
    <div class="d-print-none">
        <h3>Document(s) joint(s)</h3>

        {% if intervention.documents | length > 0 %}
            <table class='table table-bordered table-hover'>
                <tr>
                    {% for document in intervention.documents %}
                    <td>
                        <a href="{{ path('document_show', { 'id': document.id }) }}">
                            {% if 'image' in document.mime %}
                                <img src="{{ document | apptravaux_download | imagine_filter('actravaux_thumb') }}"
                                     alt="img"/>
                            {% else %}
                                <i class="fas fa-download"></i>
                                <a href="{{ absolute_url(document | apptravaux_download ) }}">Télécharger</a>
                            {% endif %}
                        </a>
                    </td>
                    {% if loop.index is divisible by(2) %}
                </tr>
                <tr>
                    {% endif %}
                    {% endfor %}
                    {% if intervention.documents | length is not divisible by(2) %}
                        <td></td>
                    {% endif %}
                </tr>
            </table>
        {% endif %}
    </div>
{% endif %}

src/AcMarche/Travaux/templates/travaux/intervention/edit.html.twig
{% extends '@AcMarcheTravaux/travaux/layout.html.twig' %}

{% block body -%}

    <div class="card bg-light mb-3">
        <div class="card-header">
            <h3>Edition de <strong>{{ entity }}</strong></h3>
        </div>
        <div class="card-body">
            {% include '@AcMarcheTravaux/travaux/intervention/form.html.twig' %}
        </div>
    </div>

    <br/>
    <a href="{{ path('intervention_show',{'id':entity.id}) }}"><i
                class="fas fa-arrow-left"></i> Annuler</a>

{% endblock %}

src/AcMarche/Travaux/templates/travaux/intervention/form.html.twig
{{ form_start(form, { 'attr': {'class': 'well'} }) }}
{{ form_errors(form) }}
<div class="row">
    <div class="col-md-6">
        {{ form_row(form.intitule) }}
    </div>
    <div class="col-md-6">
        {% if form.priorite is defined %}
            {{ form_row(form.priorite) }}
        {% endif %}
    </div>
</div>

<div class="row">
    <div class="col-md-6">

        <div class="row">

            <div class="col-md-6">
                {{ form_row(form.categorie) }}
            </div>

            <div class="col-md-6">
                {{ form_row(form.domaine) }}
            </div>
        </div>
    </div>

    <div class="col-md-6">
        {{ form_row(form.date_rappel) }}
    </div>

</div>


<div class="row">
    <div class="col-md-6">
        <div class="row">

            <div class="col-md-6">
                {{ form_row(form.service) }}
            </div>
            <div class="col-md-6">
                {{ form_row(form.batiment) }}
            </div>
        </div>
    </div>

    <div class="col-md-6">

        {{ form_row(form.date_execution) }}
        {{ form_row(form.transmis) }}
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        {% if form.etat is defined %}
            {{ form_row(form.etat) }}
        {% endif %}
    </div>

    <div class="col-md-6">

        {{ form_row(form.affectation) }}
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        {% if not is_granted('ROLE_TRAVAUX_ADMIN') %}
            <div class="alert alert-warning">
                Pour le descriptif, pensez à bien détailler<br/>
                (Metré, quantités...)
            </div>
        {% endif %}
        {{ form_row(form.descriptif) }}
    </div>
    <div class="col-md-6">
        {{ form_row(form.affectePrive) }}
        {{ form_row(form.soumis_le) }}

        <div class="row">
            <div class="col-md-6">
                {{ form_row(form.cout_main) }}
            </div>
            <div class="col-md-6">
                {{ form_row(form.cout_materiel) }}
            </div>
        </div>

    </div>
</div>


<div class="row">
    <div class="col-md-6">
        {{ form_row(form.solution) }}
    </div>
    <div class="col-md-6">
        {{ form_row(form.date_solution) }}
    </div>
</div>

{{ form_end(form) }}

src/AcMarche/Travaux/templates/travaux/intervention/index.html.twig
{% extends '@AcMarcheTravaux/travaux/layout.html.twig' %}
{% block body %}

    <div class="page-header">
        <h3>Liste des interventions ({{ interventions | length }})</h3>
    </div>

    {% include '@AcMarcheTravaux/travaux/search/intervention.html.twig' %}

    {% if interventions | length > 0 %}

        <table class='table table-bordered table-hover'>
            <thead>
            <tr>
                <th scope="col">Numéro</th>
                <th scope="col">Intitule</th>
                <th scope="col">Dernier suivis</th>
                <th scope="col">Type</th>
                <th scope="col" class="hidden-xs">Etat</th>
                <th scope="col" class="hidden-xs">Transmis</th>
                <th scope="col">Priorité</th>
                <th scope="col" class="hidden-xs" style="width: 10%;">Validé le</th>
                <th scope="col">Encodé par</th>
                <th scope="col" class="hidden-xs">Affection</th>
            </tr>
            </thead>
            <tbody>
            {% for intervention in interventions %}

                {% set class = '' %}
                {% set title = '' %}
                {% if intervention.priorite == 'Haute' and intervention.etat != 'Clôturé' %}
                    {% set class = 'table-danger' %}
                {% endif %}

                {% if workflow_has_marked_place(intervention, 'auteur_checking') %}
                    {% set class = 'table-info' %}
                    {% set title = 'Intervention doit être validée par un auteur' %}
                {% endif %}
                {% if workflow_has_marked_place(intervention, 'admin_checking') %}
                    {% set class = 'table-info' %}
                    {% set title = 'Intervention doit être validée par un admin' %}
                {% endif %}

                <tr class="{{ class }}" id="{{ intervention.id }}" title="{{ title }}">
                    <td>
                        {% if anchor == intervention.id %}
                            <i class="fas fa-arrow-right"></i>
                        {% endif %}

                        {{ intervention.id }}

                        {% if intervention.etat == 'En attente' %}
                            <br/>  <i class="far fa-hourglass" title="{{ intervention.etat }}"></i>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{{ path('intervention_show', { 'id': intervention.id }) }}"
                           title="Détail de l'intervention">{{ intervention.intitule }}</a>
                    </td>
                    <td>{{ intervention.lastsuivi | slice(0, 200) }}</td>
                    <td>{{ intervention.domaine }}</td>
                    <td class="hidden-xs">{{ intervention.etat }}</td>
                    <td class="hidden-xs">
                        {% if intervention.transmis %}
                            <i class="fas fa-check"></i>
                        {% endif %}
                    </td>
                    <td>{{ intervention.priorite }}</td>
                    <td class="hidden-xs">
                        {% if intervention.dateValidation %}
                            {{ intervention.dateValidation | date('d-m-Y') }}
                        {% endif %}
                    </td>
                    <td>{{ intervention.useradd }}</td>
                    <td class="hidden-xs">{{ intervention.affectation }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

src/AcMarche/Travaux/templates/travaux/intervention/new.html.twig
{% extends '@AcMarcheTravaux/layout.html.twig' %}

{% block body -%}

    <div class="card bg-light mb-3">
        <div class="card-header">
            <h3>Nouvelle intervention</h3>
        </div>
        <div class="card-body">
            {% include '@AcMarcheTravaux/travaux/intervention/form.html.twig' %}
        </div>
    </div>

{% endblock %}

src/AcMarche/Travaux/templates/travaux/intervention/panel.html.twig
<div class="card bg-light mb-3">
    <div class="card-header">
        <h3>{{ intervention }}</h3>
        {% if intervention.etat == 'En attente' %}
            <i class="float-right far fa-hourglass" title="{{ intervention.etat }}"></i>
        {% endif %}
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <table class='table table-bordered table-hover'>
                    <tr>
                        <th>
                            Numéro:
                        </th>
                        <td>
                            {{ intervention.id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Priorité:
                        </th>
                        <td>
                            {{ intervention.priorite }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <i class="far fa-calendar-alt"></i> Demandé le:
                        </th>
                        <td>
                            {{ intervention.createdAt | date('d-m-Y') }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <i class="far fa-calendar-alt"></i> Reporté au:
                        </th>
                        <td>
                            {% if intervention.dateExecution %}
                                {{ intervention.dateExecution | date('d-m-Y') }}
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <i class="far fa-calendar-alt"></i> Validé le:
                        </th>
                        <td>
                            {% if intervention.datevalidation %}
                                {{ intervention.datevalidation | date('d-m-Y') }}
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Type:
                        </th>
                        <td>
                            {{ intervention.domaine }}
                        </td>
                    </tr>

                    <tr>
                        <th>
                            Service:
                        </th>
                        <td>
                            {{ intervention.service }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Bâtiment:
                        </th>
                        <td>
                            {{ intervention.batiment }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Catégorie
                        </th>
                        <td>
                            {{ intervention.categorie }}
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-md-6">
                <table class='table table-bordered table-hover'>
                    <tr>
                        <th>
                            Etat:
                        </th>
                        <td>
                            {{ intervention.etat }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <i class="far fa-calendar-alt"></i> Date rappel:
                        </th>
                        <td>
                            {% if intervention.daterappel %}
                                {{ intervention.daterappel | date('d-m-Y') }}
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <i class="fas fa-user"></i>
                            <strong>Affectation:</strong>
                        </th>
                        <td>
                            {{ intervention.affectation | nl2br }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <strong>Affecté à un privé</strong>
                        </th>
                        <td>
                            {% if intervention.affectePrive %}
                                Oui
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Transmis:
                        </th>
                        <td>
                            {% if intervention.transmis %}
                                <i class="fas fa-check"></i>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <i class="far fa-calendar-alt"></i> Soumis le
                        </th>
                        <td>
                            {% if intervention.soumisle %}
                                {{ intervention.soumisle | date('d-m-Y') }}
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <i class="fas fa-euro-sign"></i> Coût en main
                            d'oeuvre:
                        </th>
                        <td>
                            {% if intervention.coutmain %}
                                {{ intervention.coutmain | number_format(2, ',', ' ') }} €
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <i class="fas fa-euro-sign"></i><strong> Coût en
                                matériel:</strong>
                        </th>
                        <td>
                            {% if intervention.coutmateriel %}
                                {{ intervention.coutmateriel | number_format(2, ',', ' ') }} €
                            {% endif %}
                        </td>
                    </tr>
                    {% set total = intervention.coutmain + intervention.coutmateriel %}
                    {% if total > 0 %}
                        <tr>
                            <th>
                                <span class="text-warning">Soit un total de</span>
                            </th>
                            <td>
                                <span class="text-warning">{{ total | number_format(2, ',', ' ') }} €</span>
                            </td>
                        </tr>
                    {% endif %}
                    <tr>
                        <th>
                            <i class="far fa-calendar-alt"></i> Date de solution:
                        </th>
                        <td>
                            {% if intervention.datesolution %}
                                {{ intervention.datesolution | date('d-m-Y') }}
                            {% endif %}
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-md-12">
                <br/>
                <p class="card-text">{{ intervention.descriptif | nl2br }}</p>

                {% if intervention.solution %}
                    <h4 class="text-success">Solution apportée:</h4>
                    {{ intervention.solution | nl2br }}
                {% endif %}
                <br/>
            </div>
        </div>
    </div>
    {% if not pdf %}
        <div class="card-footer text-muted">
        <span class="text-muted">
                {{ 'Created' | trans }} {{ intervention.createdAt|date('d-m-Y H:i:s') }} par {{ intervention.useradd }}
                . {{ 'Updated' | trans }} {{ intervention.updatedAt|date('d-m-Y H:i:s') }}
            </span>
            {% if intervention.archive %}
                <i class="float-right fas fa-archive" title="Archive"></i>
            {% endif %}
        </div>
    {% endif %}
</div>

src/AcMarche/Travaux/templates/travaux/intervention/suivis.html.twig
{% if suivis | length > 0 %}

    <h3>Suivis</h3>
    {{ form_start(form, { 'attr': {'class': 'well'} }) }}
    {{ form_errors(form, { 'attr': {'class': 'well'} }) }}

    <button type="submit" name="delete" class="btn btn-danger btn-sm float-right d-print-none">
        <i class="fas fa-trash"></i> Supprimer le(s) suivi(s)
    </button>
    <br/>
    <div class="clear-fix"></div>
    <br/>
    {% for suivi in suivis %}
        <div class="card bg-light mb-3">

            <div class="card-body">
                <p class="card-text">
                    {{ suivi.descriptif }}
                </p>
            </div>

            <div class="card-footer text-muted">
                {{ 'Created' | trans }} {{ suivi.createdAt|date('d-m-Y H:i:s') }} par {{ suivi.useradd }}
                . {{ 'Updated' | trans }} {{ suivi.updatedAt|date('d-m-Y H:i:s') }}
                {% include '@AcMarcheTravaux/travaux/intervention/actions_suvi.html.twig' %}
            </div>
        </div>
    {% endfor %}
    {{ form_end(form) }}
{% endif %}